### ISSUE TITLE
EPSG issues

### ISSUE THREAD

**Issue by august-zhu** [gipong/shp2geojson.js#18]
Hi, I have a question regarding the EPSG input box. This input parameter can be skipped if the zipped shapefile has its projection (.prj) file. But what about a shapefile without projection? But I still don't get what the CRS input box is actually trying to do (according to the code, all the user EPSG would be reprojected into EPSG 4326 in the TransCoord function).

Thanks!

**Comment by gipong** [comment]
Hi,
If you upload the shapefile without projection, you will need to  specify the EPSG code for this shapefile or use the default value (EPSG 4326).  Hope this information will help.
