### ISSUE TITLE
Problem encountered when converting files encoded in GBK

### ISSUE THREAD

**Issue by Theropod** [gipong/shp2geojson.js#5]
I tried to convert a  shapefile whose dbf file is encoded in **GBK**, but it turned out that the Chinese Attribute names were wrong. It looks like the program had read more bytes than it shoud have, and this also affected the reading of the attributes after it. 
Here's an example:
![image](https://cloud.githubusercontent.com/assets/22598638/23254723/f8142c32-f9f3-11e6-9af0-40782f344bad.png)
English names won't cause this problem, curious that if there's any solution.

**Comment by garyvidal** [comment]
I suspect this line is the problem in preprocess.js with the use of offset.  It seems the offset  has issues when the field is FLOAT for the reading of float values.  What I found is that by just setting this to count += 1 it resolved the issue.  Another thing I noticed is that floats are parsed using REGEX pattern, which probably better to check if the value is a float using if(o.fields[j].type === "F") { set property}

324.                             count += offset;

**Comment by gipong** [comment]
@garyvidal You're right!

Yes, it had read more bytes than it should have.
I found that GBK encoding and Big5 encoding store Chinese character in the same way.
Every Chinese character is represented by two bytes. 

So may be you can modify the code below by adding the gbk to make offset become two

preprocess.js
`offset = (encoding.match(/big5|gbk/i))?2:3;`

Here is the result encoding in GBK
![gbk_encoding](https://cloud.githubusercontent.com/assets/2090517/24034671/396645ea-0b2d-11e7-85ae-8dc67b8a63c2.png)

**Comment by Theropod** [comment]
Yes, it solved my problem. Thanks a lot!

**Comment by xioayaohou** [comment]
Why parse zip files can be resolved without garbled, some have garbled.
